# Generated by Django 3.1.7 on 2022-10-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default='undifined', max_length=255),
        ),
    ]
